# Form implementation generated from reading ui file 'gui_VotingMenu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1_VoteMenu(object):
    def setupUi(self, MainWindow1_VoteMenu):
        MainWindow1_VoteMenu.setObjectName("MainWindow1_VoteMenu")
        MainWindow1_VoteMenu.resize(212, 226)
        MainWindow1_VoteMenu.setMinimumSize(QtCore.QSize(212, 226))
        MainWindow1_VoteMenu.setMaximumSize(QtCore.QSize(212, 226))
        MainWindow1_VoteMenu.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow1_VoteMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.VoteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.VoteButton.setGeometry(QtCore.QRect(30, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VoteButton.setFont(font)
        self.VoteButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.VoteButton.setObjectName("VoteButton")
        self.ExitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ExitButton.setGeometry(QtCore.QRect(30, 120, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ExitButton.setFont(font)
        self.ExitButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.ExitButton.setObjectName("ExitButton")
        self.VoteMenuLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.VoteMenuLabel.setGeometry(QtCore.QRect(16, 9, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.VoteMenuLabel.setFont(font)
        self.VoteMenuLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VoteMenuLabel.setObjectName("VoteMenuLabel")
        self.HorizontalLine = QtWidgets.QFrame(parent=self.centralwidget)
        self.HorizontalLine.setGeometry(QtCore.QRect(17, 39, 181, 31))
        self.HorizontalLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.HorizontalLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.HorizontalLine.setObjectName("HorizontalLine")
        MainWindow1_VoteMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow1_VoteMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 212, 21))
        self.menubar.setObjectName("menubar")
        MainWindow1_VoteMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow1_VoteMenu)
        self.statusbar.setObjectName("statusbar")
        MainWindow1_VoteMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow1_VoteMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow1_VoteMenu)

    def retranslateUi(self, MainWindow1_VoteMenu):
        _translate = QtCore.QCoreApplication.translate
        MainWindow1_VoteMenu.setWindowTitle(_translate("MainWindow1_VoteMenu", "VotingMenu"))
        self.VoteButton.setText(_translate("MainWindow1_VoteMenu", "Vote"))
        self.ExitButton.setText(_translate("MainWindow1_VoteMenu", "Exit"))
        self.VoteMenuLabel.setText(_translate("MainWindow1_VoteMenu", "VOTE MENU"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow1_VoteMenu = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1_VoteMenu()
    ui.setupUi(MainWindow1_VoteMenu)
    MainWindow1_VoteMenu.show()
    sys.exit(app.exec())
