# Form implementation generated from reading ui file 'gui_CandidateMenu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2_CandidateMenu(object):
    def setupUi(self, MainWindow2_CandidateMenu):
        MainWindow2_CandidateMenu.setObjectName("MainWindow2_CandidateMenu")
        MainWindow2_CandidateMenu.resize(212, 226)
        MainWindow2_CandidateMenu.setMinimumSize(QtCore.QSize(212, 226))
        MainWindow2_CandidateMenu.setMaximumSize(QtCore.QSize(212, 226))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow2_CandidateMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.VoteMenuLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.VoteMenuLabel.setGeometry(QtCore.QRect(10, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.VoteMenuLabel.setFont(font)
        self.VoteMenuLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.VoteMenuLabel.setObjectName("VoteMenuLabel")
        self.HorizontalLine = QtWidgets.QFrame(parent=self.centralwidget)
        self.HorizontalLine.setGeometry(QtCore.QRect(10, 40, 191, 31))
        self.HorizontalLine.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.HorizontalLine.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.HorizontalLine.setObjectName("HorizontalLine")
        self.JohnButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.JohnButton.setGeometry(QtCore.QRect(30, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.JohnButton.setFont(font)
        self.JohnButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.JohnButton.setMouseTracking(False)
        self.JohnButton.setObjectName("JohnButton")
        self.JaneButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.JaneButton.setGeometry(QtCore.QRect(30, 120, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.JaneButton.setFont(font)
        self.JaneButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.JaneButton.setObjectName("JaneButton")
        MainWindow2_CandidateMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow2_CandidateMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 212, 21))
        self.menubar.setObjectName("menubar")
        MainWindow2_CandidateMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow2_CandidateMenu)
        self.statusbar.setObjectName("statusbar")
        MainWindow2_CandidateMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2_CandidateMenu)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2_CandidateMenu)

    def retranslateUi(self, MainWindow2_CandidateMenu):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2_CandidateMenu.setWindowTitle(_translate("MainWindow2_CandidateMenu", "CandidateMenu"))
        self.VoteMenuLabel.setText(_translate("MainWindow2_CandidateMenu", "CANDIDATE MENU"))
        self.JohnButton.setText(_translate("MainWindow2_CandidateMenu", "John"))
        self.JaneButton.setText(_translate("MainWindow2_CandidateMenu", "Jane"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2_CandidateMenu = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2_CandidateMenu()
    ui.setupUi(MainWindow2_CandidateMenu)
    MainWindow2_CandidateMenu.show()
    sys.exit(app.exec())
